services:
  app:
    image: obnoxieux/skylarks-app-config:latest
    restart: unless-stopped
    networks:
      - proxy
    #ports:
    #  - '8080:8080'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skylarks-app-config.rule=Host(`config.app.berlinskylarks.de`)"
      - "traefik.http.routers.skylarks-app-config.entrypoints=websecure"
      - "traefik.http.routers.skylarks-app-config.tls.certresolver=letsEncrypt"
      - "traefik.docker.network=proxy"
    volumes:
      - config_data:/app/

volumes:
  config_data:

networks:
  proxy:
    external: true
